apiVersion: jobs.github.com/v1
kind: ClusterScan
metadata:
  labels:
    app.kubernetes.io/name: sc-basic-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterscan
spec:
  # TODO(user): Add fields here
